name: CI/CD
on: 
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.2.0

      - name: Install
        run: yarn install --frozen-lockfile

      # - name: Lint
      #   run: yarn graphql-codegen && yarn tsc

      # - name: Jest tests
      #   run: yarn jest --ci

      # - name: Build
      #   run: yarn next build
      #   env:
      #     NEXT_PUBLIC_GRAPHQL_API_URL: https://dev.stately.ai/registry/api/graphql
      #     NEXT_PUBLIC_SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
      #     NEXT_PUBLIC_SUPABASE_ANON_API_KEY: ${{ secrets.SUPABASE_ANON_API_KEY }}
      #     NEXT_PUBLIC_USE_LOCAL_MONACO: 'true'
      #     CI: 'false'

      - name: Cypress run
        if: always()
        uses: cypress-io/github-action@v2
        with:
          browser: 'Replay Chromium'
          # start the application before running Cypress
          start: yarn start
          wait-on: http://localhost:3000
        env:
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
          # These two are here to help with measuring the true overhead by disabling diagnostics
          RECORD_REPLAY_DISABLE_ASSERTS: 1
          RECORD_REPLAY_DISABLE_SOURCEMAP_COLLECTION: 1

      - name: Upload replays ▶️
        if: always()
        uses: replayio/action-upload@v0.4.3
        with:
          api-key: rwk_b2DVaeVbmbc9I01YF1dU0ND88ZPrOGAazK40ciN4i1W
          public: true

