name: CI/CD

on: [push]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.2.0

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn graphql-codegen && yarn tsc

      - name: Jest tests
        run: yarn jest --ci

      - name: Build
        run: yarn next build
        env:
          NEXT_PUBLIC_GRAPHQL_API_URL: https://dev.stately.ai/registry/api/graphql
          NEXT_PUBLIC_SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_API_KEY: ${{ secrets.SUPABASE_ANON_API_KEY }}
          NEXT_PUBLIC_USE_LOCAL_MONACO: 'true'
          CI: 'false'

      - name: Run Cypress
        uses: replayio/action-cypress@v0.1.7
        with:
          command: npm run e2e:build -- -- --
          browser: "Replay Firefox"
          apiKey: ${{ secrets.CYPRESS_REPLAY_API_KEY }}
          public: true
          issue-number: ${{ github.event.pull_request.number }}
          upload-all: true
