name: Original Cypress Tests
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  original-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.2.0

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: yarn start
          wait-on: http://localhost:3000
