name: Original Cypress Tests
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  original-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.2.0

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn graphql-codegen && yarn tsc

      - name: Jest tests
        run: yarn jest --ci

      - name: Build
        run: yarn next build
        env:
          NEXT_PUBLIC_GRAPHQL_API_URL: https://dev.stately.ai/registry/api/graphql
          NEXT_PUBLIC_USE_LOCAL_MONACO: 'true'
          CI: 'false'

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve
          wait-on: http://localhost:3000
