name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      browser:
        description: Cypress browser to use

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.2.0

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn graphql-codegen && yarn tsc

      - name: Jest tests
        run: yarn jest --ci

      - name: Run Cypress
        uses: replayio/action-cypress@ryan/long-upload
        with:
          command: npm run e2e:server -- -- -- --spec cypress/integration/inspector.spec.ts
          browser: "Replay Firefox"
          api-key: ""
          public: true
          upload-all: true
