name: E2E Test
on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

jobs:
  cypress-tests:
    strategy:
      fail-fast: false
      matrix:
        record: ["record", "no-record"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.2.0

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn graphql-codegen && yarn tsc

      - name: Jest tests
        run: yarn jest --ci

      - name: Run Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: "Replay Chromium"
          start: yarn start
          wait-on: http://localhost:3000
        env:
          RECORD_ALL_CONTENT: 1
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata

      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.3
        with:
          api-key: ${{ secrets.RECORD_REPLAY_API_KEY }}
